### ISSUE TITLE
Time library

### ISSUE THREAD

**Issue by jpaustin** [fowlerk/ESP8266-Color-Weather-Station-v11d#1]
I see the Time library is now used. Which one as I found a few different ones. I'll assume it's the one from the guy doing the Teensy devices. If not please advise.  Getting strange compile errors with the above. 

WeMos_Weather_Station_Color_OnDemandPortal_DST_11d:928: error: 'localtime' was not declared in this scope

  struct tm * timeinfo = localtime(&now);

**Comment by fowlerk** [comment]
Ahh, I'd forgotten about that change...it actually brought back some nightmares that I had around the Time libraries.  Here's the quick fix, admittedly not pretty, but it is what I did to get it running.  Download and install the library from Michael Margolis (the "Teensy Guy" I think you referenced) here:  https://github.com/michaelmargolis/arduino_time/tree/master/Time .  Install, then rename the two functions in the library folder Time.cpp and Time.h (I used something like TimeMM.cpp and TimeMM.h).  This will allow the code to compile correctly.

Gory details:  The Arduino time library is a mess, the extent of which I didn't realize until I tried to use some of the new functions (it appears that the currently popular supported library is the one from Paul Stoffregen here https://github.com/PaulStoffregen/Time).  (Looks like this is the original Margolis library, but now supported by Paul.)  The existing Weather Station code came from an example by Neptune that provides the DST functionality, and relies on the function localtime that breaks the time into components used by the display.  This is a holdover from the original C library time functions (from the Arduino core), which has now been renamed to breaktime.  Unfortunately, it isn't quite that simple, as I found when I tried to simply use the newest time library and rename this call that the time structure was also modified.  A whole new can of worms.  At the time, I didn't have time to rewrite the entire code segment, so I simply renamed the Time.h/.cpp from Margolis so that the original Time.h/.cpp from the Arduino core would be used instead.  I'd planned on revisiting this to clean it up but never did.  Now that you've made me relive this nightmare ;) I'll try to go back and fix this so that it uses the latest supported TimeLib library by Paul.

Sorry for the mess, let me know if this doesn't fix the issue temporarily or if my instructions don't make sense.

**Comment by jpaustin** [comment]
I'll try it if I get time in the next few days (unlikely). If you can redo the code to work with the latest Paul S. TIME library that would be awesome but I know what type of commitment that often is ;-)

In general I think the rev11 appears to be well worth the pain. 

.ps I did manage to have some  weather alerts last night and had a chance to test out the rev9 code. Nice!

**Comment by fowlerk** [comment]
Excellent, glad you were able to see the alerts...one of my favorite new features.  I'll try to find time to convert the code to the latest Time lib over the next week or so and will let you know how that progresses.

**Comment by fowlerk** [comment]
After looking at this more closely, I realized I had removed the new function calls for which I'd originally included the TimeLib library, and used a different approach that didn't require them.  So, I could safely remove the #include for the TimeLib lib and revert back to the original (core) time lib.  So, though not ideal in that support is moving towards TimeLib (it seems anyway), this is the same as all the previous versions of the Weather Station code.  Please try again to compile it and let me know if you have any issues.

At some point, I may still look to replace time with TimeLib, but at least this should avoid the file renaming kludge I'd previously suggested.

**Comment by jpaustin** [comment]
Time is not giving me any issues for now. Now seeing new issue. Will open unique comment for that one.

**Comment by fowlerk** [comment]
Okay, closing this one.

**Comment by jpaustin** [comment]
BTW posted a tweet using the hashtag #fowlerk for my latest build. Thanks again for all the effort. A great project.

**Comment by fowlerk** [comment]
Thanks JP...appreciate the tweet, and glad someone else finds it useful!  FWIW, my Twitter handle is @kf_fowler.
